language: ruby
bundler_args: --without development
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode
env:  
  - "TRAVIS=1"
  -
    global:
      - "JRUBY_OPTS=-Xcext.enabled=true"
  
